### ISSUE TITLE
v1.0.3 causes java.lang.IllegalArgumentException: java.io.EOFException on certain Tomcat War deployments

### ISSUE THREAD

**Issue by gregorkistler** [apache/tomcat-jakartaee-migration#34]
Hi,

couldn't wait to try out the latest and greatest version released a couple of days ago as it fixes e.g. #29 
Unfortunately I ran into another issue but I'm not quite sure if it's the right repo to report or if it's something Tomcat-related. As it doesn't happen with v1.0.0 I guess it's the Tomcat Migration Tool and not Tomcat though.

I'm using a Dockerfile to build/create my web application as a WAR file and migrate jars (roughly 30) in my project.

The expected output when I start the container via Docker Compose would be something like:
```
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
13-Sep-2022 10:50:00.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.1.0-M17
13-Sep-2022 10:50:00.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jul 13 2022 18:51:03 UTC
13-Sep-2022 10:50:00.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.1.0.0
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.0-46-generic
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           17.0.4.1+1
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
13-Sep-2022 10:50:00.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
13-Sep-2022 10:50:00.509 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
13-Sep-2022 10:50:00.517 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
13-Sep-2022 10:50:00.517 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
13-Sep-2022 10:50:00.517 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
13-Sep-2022 10:50:00.517 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
13-Sep-2022 10:50:00.517 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
13-Sep-2022 10:50:00.518 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
13-Sep-2022 10:50:00.525 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [2.0.1] using APR version [1.7.0].
13-Sep-2022 10:50:00.529 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
13-Sep-2022 10:50:00.735 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
13-Sep-2022 10:50:00.759 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [389] milliseconds
13-Sep-2022 10:50:00.797 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
13-Sep-2022 10:50:00.797 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.1.0-M17]
13-Sep-2022 10:50:00.811 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
13-Sep-2022 10:50:01.197 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
13-Sep-2022 10:50:01.231 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [420] ms
13-Sep-2022 10:50:01.234 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
13-Sep-2022 10:50:01.243 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [484] milliseconds
```

The error I get is:

```
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
13-Sep-2022 10:49:31.037 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.1.0-M17
13-Sep-2022 10:49:31.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jul 13 2022 18:51:03 UTC
13-Sep-2022 10:49:31.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.1.0.0
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.0-46-generic
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           17.0.4.1+1
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
13-Sep-2022 10:49:31.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
13-Sep-2022 10:49:31.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
13-Sep-2022 10:49:31.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
13-Sep-2022 10:49:31.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
13-Sep-2022 10:49:31.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
13-Sep-2022 10:49:31.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
13-Sep-2022 10:49:31.059 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [2.0.1] using APR version [1.7.0].
13-Sep-2022 10:49:31.063 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
13-Sep-2022 10:49:31.289 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
13-Sep-2022 10:49:31.308 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [408] milliseconds
13-Sep-2022 10:49:31.341 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
13-Sep-2022 10:49:31.341 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.1.0-M17]
13-Sep-2022 10:49:31.354 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
13-Sep-2022 10:49:31.403 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
	java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1950)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:777)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1657)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:310)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:252)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:926)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@2dfaea86]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
		at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:737)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4833)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4971)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
		... 37 more
	Caused by: java.lang.IllegalArgumentException: java.io.EOFException: Expected:46, read:0
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:142)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		... 44 more
	Caused by: java.io.EOFException: Expected:46, read:0
		at java.base/java.util.jar.JarFile.getBytes(JarFile.java:818)
		at java.base/java.util.jar.JarFile.getManifestFromReference(JarFile.java:420)
		at java.base/java.util.jar.JarFile.getManifest(JarFile.java:407)
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:140)
		... 45 more
13-Sep-2022 10:49:31.405 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [51] ms
13-Sep-2022 10:49:31.407 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
13-Sep-2022 10:49:31.416 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [108] milliseconds
```

After having a look at the jars and the file size differences between migrated ones with 1.0.0 and 1.0.3 I could figure out four jars where I can reproduce the issue at any time.
As a reproducer I've written a simple Dockerfile which:

- makes use of the [Tomcat Sample Application](https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/)
- downloads the jars from Maven Repository
- downloads the Tomcat Migration Tool from Maven Repository

```Dockerfile
# syntax=docker/dockerfile:1

FROM tomcat:10.1.0-M17

ARG MIG_VER=1.0.0
ARG MVN_URL=https://repo1.maven.org/maven2

WORKDIR /jar-java

RUN apt-get -qq update; \
        apt-get install -y --no-install-recommends -qq zip unzip wget; \
        wget -q "${MVN_URL}/isorelax/isorelax/20020414/isorelax-20020414.jar"; \
        wget -q "${MVN_URL}/net/java/dev/jna/jna-platform/4.5.1/jna-platform-4.5.1.jar"; \
        wget -q "${MVN_URL}/msv/msv/20020414/msv-20020414.jar"; \
        wget -q "${MVN_URL}/relaxngDatatype/relaxngDatatype/20020414/relaxngDatatype-20020414.jar"; \
        wget -q "${MVN_URL}/org/apache/tomcat/jakartaee-migration/${MIG_VER}/jakartaee-migration-${MIG_VER}-shaded.jar" -O /jakartaee-migration.jar; \
        java -jar /jakartaee-migration.jar \
#               -exclude=isorelax* \
#               -exclude=jna-platform* \
#               -exclude=msv* \
#               -exclude=relaxngDatatype* \
        /jar-java /jar-jakarta; \
        wget -q "https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war"; \
        unzip sample.war; \
        cp -r /jar-jakarta/*.jar WEB-INF/lib; \
        zip -r /usr/local/tomcat/webapps/ROOT.war WEB-INF META-INF hello.jsp images index.html

WORKDIR /usr/local/tomcat
```

If you build a container image using something like `docker buildx build --progress plain -t sample-war .` and create a container like `docker run --rm sample-war` the web application gets deployed as expected.
If you change the version (line 5) in the Dockerfile from `1.0.0` to `1.0.3`, build the image and create the container again you will end up with the posted java.io.EOFException.
If you **exclude** (uncomment lines 18 to 21 in the Dockerfile) all four jars and do the same again the application again gets deployed as expected.

Would be great if we could sort this out somehow. Unfortunately I don't get any more detailed logs even if I set the log level to `FINEST` in the web application itself and Tomcat.

TIA

**Comment by gregorkistler** [comment]
No worries and thanks for the quick response :)

**Comment by aooohan** [comment]
> After having a look at the jars and the file size differences between migrated ones with 1.0.0 and 1.0.3 I could figure out four jars where I can reproduce the issue at any time.

This is entirely due to my unfamiliarity with the apache-commons-compress tool. I didn't read its java doc carefully, which led me to write a wrong code implementation that caused this.

After a few tests, I think I have fixed the problem. Thanks to the detailed steps you provided to reproduce it, I was able to solve the issue so smoothly.

**Comment by gregorkistler** [comment]
Sweet! Thank you. I can confirm that commit adc4ec5b8f3375bfc98d35f694fd6a0cc75f29f1 fixes the issue 🥳
